io:
  video_dir_path: /home/alex/workspace/video_feature_extraction/videos
  out_path: /home/alex/workspace/video_feature_extraction/results
inference:
  device: cuda
  batch_size: 32
  num_workers: 4
  prefetch_factor: 2
  frame_window: 16
  stride: 4
model:
  ckpt: sports1m
  side_size: 288
  crop_size: 112
  mean:
  - 0.5
  - 0.5
  - 0.5
  std:
  - 0.5
  - 0.5
  - 0.5
  crop: five_crops
  mirror: true
model_module_str: models.c3d
