io:
  video_dir_path:  /home/alex/workspace/video_feature_extraction/videos
  out_path: /home/alex/workspace/video_feature_extraction/results
inference:
  device: cuda:1
  batch_size: 2
  num_workers: 8
  prefetch_factor: 3
  frame_window: 32
  stride: 16
model:
  ckpt: "omnivore_swinB_imagenet21k"
  side_size: 224
  crop_size: 224
  dilation: 1
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  crop: three_crops
  mirror: true
model_module_str: models.omnivore
